# Generated by Django 4.2.2 on 2023-07-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='수정일')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='작성일')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.CharField(blank=True, max_length=20, verbose_name='내용')),
                ('region', models.CharField(blank=True, max_length=20, verbose_name='지역')),
                ('price', models.IntegerField(default=1000, verbose_name='가격')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user', verbose_name='작성자')),
            ],
        ),
    ]
